name: PR Checker

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR Description and Title
        id: check_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -c "
          import re
          import sys
          import os

          pr_description = os.getenv('GITHUB_EVENT_PULL_REQUEST_BODY', '')
          pr_title = os.getenv('GITHUB_EVENT_PULL_REQUEST_TITLE', '')

          # Check if PR description is present
          if not pr_description:
              print('Warning: PR description is missing.')
          else:
              # Check if the PR description contains 'Fixes #<issue-number>'
              if not re.search(r'Fixes #[0-9]+', pr_description):
                  print('Error: The PR description should include Fixes #<issue-number>.')
                  sys.exit(1)

              # Check if the PR title starts with FIX, FEAT, or DOC
              if not re.match(r'^(FIX|FEAT|DOC)', pr_title):
                  print('Error: The PR title should start with FIX, FEAT, or DOC.')
                  sys.exit(1)

          print('PR description and title are valid.')
          "

      - name: Output result
        run: |
          if [ -s "${{ steps.check_pr.outputs.stderr }}" ]; then
            echo "All checks passed."
          else
            echo "There were errors during the PR check."